// @generated by `npm run generate:bindings` — do not edit manually.

// This file has been generated by Specta. Do not edit this file manually.
export type CalendarDay = {
	date: string,
	task_count: number,
	completed_count: number,
};

export type Category = {
	id: number,
	name: string,
	color: string | null,
	parent_id: number | null,
};

export type CreateTaskInput = {
	title: string,
	description: string | null,
	priority: number | null,
	due_date: string | null,
	category_id: number | null,
	recurrence_rule: string | null,
	estimated_minutes: number | null,
};

export type DailyAccuracy = {
	date: string,
	estimated_minutes: number | null,
	actual_minutes: number,
	completed_tasks: number,
	total_tasks: number,
};

export type DailyCount = {
	date: string,
	completed: number,
};

export type DailyReview = {
	date: string,
	is_workday: boolean,
	completed_tasks: ReviewTask[],
	incomplete_tasks: ReviewTask[],
	total_focus_minutes: number,
	focus_sessions: number,
	plan_accuracy: number,
};

export type DesktopPanelSnapshot = {
	today: TaskSummary[],
	overdue: TaskSummary[],
	generated_at: string,
};

export type FocusHeatmapEntry = {
	hour: number,
	minutes: number,
	sessions: number,
};

export type FocusSession = {
	id: number,
	task_id: number,
	task_title: string | null,
	started_at: string,
	ended_at: string | null,
	duration_minutes: number,
	completed: boolean,
};

export type FocusSummary = {
	total_minutes: number,
	session_count: number,
	sessions: FocusSession[],
};

export type HolidayEntry = {
	date: string,
	name: string,
};

export type ListTasksFilters = {
	status: string | null,
	category_id: number | null,
	tag_id: number | null,
	due_date: string | null,
	search_query: string | null,
	today_view: boolean | null,
	overdue_view: boolean | null,
	priority: number | null,
};

export type NotificationSettings = {
	notify_daily_summary: boolean,
	notify_daily_time: string,
	notify_overdue: boolean,
	notify_overdue_interval_minutes: string,
};

export type Reminder = {
	id: number,
	task_id: number,
	remind_at: string,
	notified: boolean,
};

export type ReviewTask = {
	id: number,
	title: string,
	estimated_minutes: number | null,
	actual_focus_minutes: number,
	priority: number,
};

export type ScheduleDay = {
	date: string,
	is_workday: boolean,
	am_block: TimeBlock,
	pm_block: TimeBlock,
	entries: ScheduleEntry[],
	unscheduled: ScheduleEntry[],
	/**  Total estimated minutes of scheduled tasks */
	scheduled_minutes: number,
	/**  Total available work minutes */
	available_minutes: number,
};

export type ScheduleEntry = {
	id: number,
	task_id: number,
	task_title: string,
	task_priority: number,
	date: string,
	start_time: string,
	duration_minutes: number,
	sort_order: number,
	completed: boolean,
	category_color: string | null,
};

export type Settings = {
	work_start_am: string,
	work_end_am: string,
	work_start_pm: string,
	work_end_pm: string,
	default_focus_minutes: string,
};

export type SortOption = {
	field: string | null,
	direction: string | null,
};

export type Statistics = {
	today_count: number,
	overdue_count: number,
	weekly_completion_rate: number,
	daily_counts: DailyCount[],
};

export type StatsPanelData = {
	statistics: Statistics,
	weekly_accuracy: WeeklyAccuracy,
	focus_heatmap: FocusHeatmapEntry[],
};

export type Subtask = {
	id: number,
	task_id: number,
	title: string,
	status: string,
	sort_order: number,
	created_at: string,
	completed_at: string | null,
};

export type SubtaskProgress = {
	total: number,
	completed: number,
};

export type Tag = {
	id: number,
	name: string,
	color: string | null,
};

export type TaskSummary = {
	id: number,
	title: string,
	status: string,
	priority: number,
	due_date: string | null,
	category_id: number | null,
	created_at: string,
	tags: Tag[],
	subtasks_progress: SubtaskProgress,
};

export type TaskWithDetails = {
	id: number,
	title: string,
	description: string | null,
	status: string,
	priority: number,
	due_date: string | null,
	category_id: number | null,
	recurrence_rule: string | null,
	recurrence_parent_id: number | null,
	estimated_minutes: number | null,
	created_at: string,
	updated_at: string,
	completed_at: string | null,
	archived_at: string | null,
	tags: Tag[],
	subtasks: Subtask[],
	reminders: Reminder[],
};

export type TimeBlock = {
	start: string,
	end: string,
	label: string,
};

export type UpdateTaskInput = {
	title: string | null,
	description: string | null,
	priority: number | null,
	due_date: string | null,
	category_id: number | null,
	estimated_minutes: number | null,
	clear_description: boolean | null,
	clear_due_date: boolean | null,
	clear_category_id: boolean | null,
	clear_estimated_minutes: boolean | null,
};

export type WeeklyAccuracy = {
	days: DailyAccuracy[],
	overall_accuracy: number,
};

export type WorkloadSummary = {
	date: string,
	is_workday: boolean,
	estimated_total_minutes: number,
	scheduled_total_minutes: number,
	actual_focus_minutes: number,
	available_minutes: number,
	task_count: number,
	completed_count: number,
};
